version: '2'
services:
  server:
    image: einaralex/tictactoe:${GIT_COMMIT}
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PORT: 3000
    depends_on:
      - postgres
    ports:
      - "80:3000"
      - "3000:3000"
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
