version: '2'
services:
  web:
    image: einaralex/tictactoe:${GIT_COMMIT}
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PORT: 3000
    links:
      - postgres
    ports:
      - "80:3000"
    env_file:
      - '.env'
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
