version: '2'
services:
  server:
    image: einaralex/tictactoe
    environment:
      - PGHOST=pg2
      - PGPORT=5432
      - PORT=8080
    depends_on:
      - pg2
    ports:
      - "8080:8080"
  pg2:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
