#!/bin/bash

echo Exporting git information
if [ -z "$GIT_COMMIT" ]; then
  export GIT_COMMIT=$(git rev-parse HEAD)
  export GIT_URL=$(git config --get remote.origin.url)
else
  echo Could not export information
fi

if [ $1 = "dockerbuild" ] ; then
    ./scripts_library/dockerbuild.sh
fi

if [ $1 = "updateaws" ] ; then
    ./provisioning/updateinstance.sh
fi
